server.port=5678
spring.application.name=INVOICE-LOGIN-SERVICE

#spring.profiles.active=uatl
# DB (Postgres)
spring.datasource.url=jdbc:postgresql://localhost:5432/Invoice
spring.datasource.username=postgres
spring.datasource.password=Lms@123$
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.preferIpAddress=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

# WebFlux
spring.main.web-application-type=reactive

spring.httpclient.enabled=false
spring.webclient.enabled=false
spring.cloud.compatibility-verifier.enabled=false

# Mail
spring.mail.host=host.narveetech.com
spring.mail.port=465
spring.mail.username=no-reply@narvee.com
spring.mail.password=4hi;lMs[,Yu66Zql
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.from=no-reply@narvee.com





# Actuator
management.endpoints.web.exposure.include=*
