spring.application.name=INVOICE-LOGIN-SERVICE

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/Invoice

spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Narvee@123$}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=invoice
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Mail
spring.mail.host=host.narveetech.com
spring.mail.port=465
spring.mail.username=no-reply@narvee.com
spring.mail.password='4hi;lMs[,Yu66Zql'
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT
# Must be at least 32 chars for HS256
jwt.secret=8f2c9a6d1e4b7c3f5a0d9e2b6c8f1a4e7d0c3b5a9f2e6d1c4b7a8e0f3d5c2b1
# 3.5 hours in ms
jwt.expiration=12600000

profile.upload-dir=uploads/profile
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

